language: node_js
node_js:
  - '0.12'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-wejs' ]; then cd .. && eval "mv $currentfolder generator-wejs" && cd generator-wejs; fi

notifications:
  email:
    - alberto@wejs.org

